// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SelectGermany.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SelectGermany")]
    public partial class SelectGermanyFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SelectGermany.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SelectGermany", "     Validate the total cartidges for the below scenarios.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate the Cartidges.")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("1", "N", "Distickstoffoxid", "10024-97-2", "UU", "", "", "", "", "", "", "", "", "", "", "0", @"3M hat keinen geeigneten Filter für einen oder mehrere der angegebenen Schadstoffe. Alternativ kann umluftunabhängiger Atemschutz, je nach Schutzfaktor des gewählten Atemschutzgeräts, geeignet sein, um einen ausreichenden Schutz zu erreichen. Weitere Informationen finden Sie unter „Ressourcen” unten oder unter +49 (0)2131 88 19 265 in Deutschland, +43 1417 00 52 in Österreich, +41 4350 896 58 in der Schweiz.", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("2", "N", "Terephthalsäure (einatembare Fraktion)", "100-21-0", "P", "", "", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "", "2135, 6035, D3135, D9035, 2125, D3125, DT-1135E", "TR-3712E, TR-6710E, DT-1135E", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+, 2135, 6035, D3135, D" +
            "9035, 2125, D3125, DT-1135E, TR-3712E, TR-6710E, DT-1135E", "19", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("3", "N", "Terephthalsäure (einatembare Fraktion)", "100-21-0", "P", "Yes", "", "", "", "", "9936, 9922, 9925, 9928, 9926, 9913, 9914", "", "6038, 2138, D3138, 2128, D3128, D9038", "TR-3822E, TR-3802E, TR-6820E", "", "", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("4", "N", "Terephthalsäure (einatembare Fraktion)", "100-21-0", "P", "No", "", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "", "2135, 6035, D3135, D9035, 2125, D3125, DT-1135E", "TR-3712E, TR-6710E, DT-1135E", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+, 2135, 6035, D3135, D" +
            "9035, 2125, D3125, DT-1135E, TR-3712E, TR-6710E, DT-1135E", "19", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("5", "N", "Terephthalsäure (einatembare Fraktion)", "100-21-0", "P", "No", "", "Disposable", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "9", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("6", "N", "Terephthalsäure (einatembare Fraktion)", "100-21-0", "P", "No", "", "Reusable", "", "", "", "", "2135, 6035, D3135, D9035, 2125, D3125, DT-1135E", "", "2135, 6035, D3135, D9035, 2125, D3125, DT-1135E", "7", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("7", "N", "Terephthalsäure (einatembare Fraktion)", "100-21-0", "P", "No", "", "PAPR", "", "", "", "", "", "TR-3712E, TR-6710E, DT-1135E", "TR-3712E, TR-6710E, DT-1135E", "3", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("8", "N", "Asbest  (bis 100.000 Fasern/m3)", "1332-21-4", "P2", "", "", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+", "", "2135, 6035, D3135, D9035, 2125, D3125, DT-1135E", "TR-3712E, TR-6710E, DT-1135E", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 2135, 6035, D3135, D9035, 2125, D3" +
            "125, DT-1135E, TR-3712E, TR-6710E, DT-1135E", "17", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("9", "N", "Asbest (100.000 - 300.000 Fasern/m3)", "1332-21-4", "P3", "", "", "", "", "", "8833, 8835+, 9330, 9332+", "", "2135, 6035, D3135, D9035, DT-1135E", "TR-3712E, TR-6710E, DT-1135E", "8833, 8835+, 9330, 9332+, 2135, 6035, D3135, D9035, DT-1135E, TR-3712E, TR-6710E," +
            " DT-1135E", "12", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("10", "N", "Asbest (300.000 - 4.000.000 Fasern/m3)", "1332-21-4", "TM3P", "", "", "", "", "", "", "", "", "TR-6710E", "TR-6710E", "1", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("11", "N", "Ethylbenzol", "100-41-4", "A", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4006E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT" +
            "-4001E, DT-4005E, DT-4006E, TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT" +
            "-4035E, DT-4036E, DT-4045E, DT-4046E", "24", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("12", "N", "Ethylbenzol", "100-41-4", "A", "", "Yes", "", "", "", "", "4251+, 4255+, 4277+, 4279+", @"6051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", @"4251+, 4255+, 4277+, 4279+, 6051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E, TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "50", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("13", "N", "Ethylbenzol", "100-41-4", "A", "", "No", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4006E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT" +
            "-4001E, DT-4005E, DT-4006E, TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT" +
            "-4035E, DT-4036E, DT-4045E, DT-4046E", "24", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("14", "N", "Ethylbenzol", "100-41-4", "A", "", "No", "Reusable", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4006E", "", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT" +
            "-4001E, DT-4005E, DT-4006E", "15", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("15", "N", "Ethylbenzol", "100-41-4", "A", "", "No", "PAPR", "", "", "", "", "", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", "9", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("16", "N", "Heptan-3-on", "106-35-4", "A/P", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", @"6051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", @"4256051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E1+, 4255+, 4277+, 4279+, TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "50", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("17", "N", "2,2\'-Dichlor-4,4\'-methylendianilin", "101-14-4", "A/P3", "", "", "", "", "", "", "", "6051+5935+501, D8051+D7935+D701, 6055+5935+501, D8055+D7935+D701, 6057+5935+501, " +
            "6075+5935+501, 6059+5935+501, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, " +
            "6092, 6099, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", @"6051+5935+501, D8051+D7935+D701, 6055+5935+501, D8055+D7935+D701, 6057+5935+501, 6075+5935+501, 6059+5935+501, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E, TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "30", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("18", "N", "Butan", "106-97-8", "AX", "", "", "", "", "", "", "", "6098, DT-4007E, DT-4047E, DT-4048E", "", "6098, DT-4007E, DT-4047E, DT-4048E", "4", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("19", "N", "Fluorwasserstoff (als F)", "7664-39-3", "HF", "", "", "", "", "", "", "4277+, 4279+", "6038, 6057, 6059, D8059, D9038, DT-4005E, DT-4006E", "TR-3822E, TR-6130E, TR-6580E, TR-6820E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", "4277+, 4279+, 6038, 6057, 6059, D8059, D9038, DT-4005E, DT-4006E, TR-3822E, TR-61" +
            "30E, TR-6580E, TR-6820E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "18", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("20", "N", "Chlordioxid", "10049-04-4", "B", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059, DT-4005E, DT-4006E", "TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "4277+, 4279+, 6057, 6059, D8059, DT-4005E, DT-4006E, TR-6130E, TR-6580E, DT-4032E" +
            ", DT-4035E, DT-4036E, DT-4045E, DT-4046E", "14", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("21", "N", "Phosphoroxytrichlorid", "10025-87-3", "B/P", "", "", "", "", "", "", "4277+, 4279+", "6057+5911+501, 6057+5925+501, 6057+5935+501, 6059+5911+501, 6059+5925+501, 6059+5" +
            "935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 6092, 6099" +
            ", DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", @"4277+, 4279+, 6057+5911+501, 6057+5925+501, 6057+5935+501, 6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 6092, 6099, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E, TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "27", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("22", "N", "Phosphorpentachlorid (Einatembare Fraktion)", "10026-13-8", "B/P\nE/P", "", "", "", "", "", "", "4277+, 4279+", "6057+5911+501, 6057+5925+501, 6057+5935+501, 6059+5911+501, 6059+5925+501, 6059+5" +
            "935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 6092, 6096" +
            ", 6099, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", @"4277+, 4279+, 6057+5911+501, 6057+5925+501, 6057+5935+501, 6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 6092, 6096, 6099, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E, TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "28", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("23", "N", "Butylmercaptan", "109-79-5", "A\nB", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4006E, " +
            "", "TR-6110E, TR-6310E, DT-4031E, TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, D" +
            "T-4045E, DT-4046E", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT" +
            "-4001E, DT-4005E, DT-4006E, TR-6110E, TR-6310E, DT-4031E, TR-6130E, TR-6580E, DT" +
            "-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "25", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("24", "N", "Trinitroglycerin", "55-63-0", "B\nA", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4006E, " +
            "", "TR-6110E, TR-6310E, DT-4031E, TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, D" +
            "T-4045E, DT-4046E", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT" +
            "-4001E, DT-4005E, DT-4006E, TR-6110E, TR-6310E, DT-4031E, TR-6130E, TR-6580E, DT" +
            "-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "25", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("25", "N", "Methylanilin", "100-61-8", "A\nK", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6054, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4" +
            "006E", "TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-4031E, DT-4035E, DT-4036E, DT-4045E, D" +
            "T-4046E", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6054, 6057, 6075, 6059, D80" +
            "59, DT-4001E, DT-4005E, DT-4006E, TR-6110E, TR-6310E, TR-6130E, TR-6580E, DT-403" +
            "1E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "25", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("26", "N", "Salzsäure", "7647-01-0", "E", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059, DT-4006E", "TR-6130E, TR-6580E, DT-4036E, DT-4045E, DT-4046E", "4277+, 4279+, 6057, 6059, D8059, DT-4006E, TR-6130E, TR-6580E, DT-4036E, DT-4045E" +
            ", DT-4046E", "11", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("27", "N", "Schwefelsäure", "7664-93-9", "E/P", "", "", "", "", "", "", "4277+, 4279+", "6057+5911+501, 6057+5925+501, 6057+5935+501,  6059+5911+501, 6059+5925+501, 6059+" +
            "5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6096, D8094, 609" +
            "2, 6099, DT-4036E, DT-4045E, DT-4046E ", "TR-6130E, TR-6580E, DT-4036E, DT-4045E, DT-4046E", @"4277+, 4279+, 6057+5911+501, 6057+5925+501, 6057+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6096, D8094, 6092, 6099, DT-4036E, DT-4045E, DT-4046E, TR-6130E, TR-6580E, DT-4036E, DT-4045E, DT-4046E ", "23", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("28", "N", "Essigsäure", "64-19-7", "E\nA\nB", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT-4001E, DT-4005E, DT-4006E ", "TR-6110E, TR-6310E, DT-4031E, TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, D" +
            "T-4045E, DT-4046E", "4251+, 4255+, 4277+, 4279+, 6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059, DT" +
            "-4001E, DT-4005E, DT-4006E , TR-6110E, TR-6310E, DT-4031E, TR-6130E, TR-6580E, D" +
            "T-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "25", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("29", "N", "Ameisensäure", "64-18-6", "E\nB", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059, DT-4005E, DT-4006E", "TR-6130E, TR-6580E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E", "4277+, 4279+, 6057, 6059, D8059, DT-4005E, DT-4006E, TR-6130E, TR-6580E, DT-4032E" +
            ", DT-4035E, DT-4036E, DT-4045E, DT-4046E", "14", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("30", "N", "Formaldehyd", "50-00-0", "Form", "", "", "", "", "", "", "", "6075", "", "6075", "1", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("31", "N", "Formaldehyd", "50-00-0", "Form", "", "Yes", "", "", "", "", "", "6075+5911+501, 6075+5925+501, 6075+5935+501, 6092, 6099", "", "6075+5911+501, 6075+5925+501, 6075+5935+501, 6092, 6099", "5", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("32", "N", "Methylamin", "74-89-5", "K", "", "", "", "", "", "", " 4279+", "6054, 6059, D8059, DT-4006E", "TR-6580E, DT-4045E, DT-4046E", " 4279+, 6054, 6059, D8059, DT-4006E, TR-6580E, DT-4045E, DT-4046E", "8", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("33", "N", "Methylamin", "74-89-5", "K", "", "Yes", "", "", "", "", "4279+", "6054+5911+501, 6054+5925+501, 6054+5935+501,  6059+5911+501, 6059+5925+501, 6059+" +
            "5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 6092, 609" +
            "9, DT-4045E, DT-4046E", "TR-6580E, DT-4045E, DT-4046E", "4279+, 6054+5911+501, 6054+5925+501, 6054+5935+501,  6059+5911+501, 6059+5925+501" +
            ", 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 60" +
            "92, 6099, DT-4045E, DT-4046E, TR-6580E, DT-4045E, DT-4046E ", "18", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("34", "N", "Quecksilber, Dampf", "7439-97-6", "Hg/P3", "", "", "", "", "", "", "", "6096, 6099, DT-4046E, DT-4049E", "TR-6580E, DT-4046E", "6096, 6099, DT-4046E, DT-4049E, TR-6580E, DT-4046E", "6", "", "Germany", new string[] {
                "source:Select_Germany.xlsx:sheet1"}, Category="source:Select_Germany.xlsx:sheet1")]
        public virtual void ValidateTheCartidges_(
                    string s_No, 
                    string is_Mixture, 
                    string contaminant, 
                    string casNumber, 
                    string recommended_Respirator, 
                    string gases_Or_Vapors_Also_Present, 
                    string particles_Present, 
                    string respirator_Type, 
                    string filter_Class, 
                    string cartidge, 
                    string disposable, 
                    string resusableFacepiece_And_Filter_Together_As_Complete_System, 
                    string resuableCartidgeFilter, 
                    string pAPRCartidgeFilter, 
                    string total_Contaminants, 
                    string total_Element_Count, 
                    string text_Message, 
                    string region, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate the Cartidges.", null, @__tags);
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
 testRunner.Given("I have navigated to the SLS Website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When(string.Format("I select the  {0} provided  and click on the next button", region), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.Then("I select Cartidge/Filter check box and proceed further till data validation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
 testRunner.And(string.Format("I have {0} and {1} to filter the product and I filter the product", casNumber, contaminant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then(string.Format("I select the filtered products using the Cas {0} or the Contaminants Value {1}", casNumber, contaminant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("Click on the next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then(string.Format("I Filter the contaminants using the filter values {0},{1},{2},{3},{4},{5} and {6}" +
                        "", gases_Or_Vapors_Also_Present, particles_Present, respirator_Type, filter_Class, cartidge, casNumber, text_Message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And(string.Format("I do the final validation of the elements with the serial no. {0} , {1},{2},{3} a" +
                        "nd {4}", s_No, casNumber, region, text_Message, total_Element_Count), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
