// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace select_service_us_canada.Mixture_Acids_Validation.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MixtureAcidValidations")]
    public partial class MixtureAcidValidationsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MixtureAcidValidations.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MixtureAcidValidations", "\tValidating the Service Life mixtures", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 Acid Validations AcetonitrileFormamide")]
        public virtual void _01AcidValidationsAcetonitrileFormamide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 Acid Validations AcetonitrileFormamide", null, ((string[])(null)));
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then("I select the AF acid and set their respective exposure values.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.Then("I filter the required cartidge/filter using the cartidge value", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("After setting up the environment details click on next button to proceed further." +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("Verify teh Service Life Estimate and then click on Done button to complete the ve" +
                    "rification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 Acid Validations HexaneStyrene")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _02AcidValidationsHexaneStyrene()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 Acid Validations HexaneStyrene", null, new string[] {
                        "regression"});
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.Then("I select the HS acid and set their respective exposure values.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for HS Acid Mixtur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.And("After setting up the environment details for HS Acid Mixture click on next button" +
                    " to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.Then("Verify the Service Life Estimate for HS Acid Mixture and then click on Done butto" +
                    "n to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 Acid Validations HFSO")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _03AcidValidationsHFSO()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 Acid Validations HFSO", null, new string[] {
                        "regression"});
#line 24
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 25
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
 testRunner.Then("I select the HFSO acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for HFSO Acid Mixt" +
                    "ure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 29
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.And("After setting up the environment details for HFSO Acid Mixture click on next butt" +
                    "on to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.Then("Verify the Service Life Estimate for HFSO Acid Mixture and then click on Done but" +
                    "ton to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04 Acid Validations AmmoniaMethylamine")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _04AcidValidationsAmmoniaMethylamine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 Acid Validations AmmoniaMethylamine", null, new string[] {
                        "regression"});
#line 34
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 35
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.Then("I select the AM acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AmmoniaMethyla" +
                    "mine Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
 testRunner.And("After setting up the environment details for AmmoniaMethylamine Acid Mixture clic" +
                    "k on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.Then("Verify the Service Life Estimate for AmmoniaMethylamine Acid Mixture and then cli" +
                    "ck on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 Acid Validations AmmoniaMethylamine_mg3")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _05AcidValidationsAmmoniaMethylamine_Mg3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 Acid Validations AmmoniaMethylamine_mg3", null, new string[] {
                        "regression"});
#line 44
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 45
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
 testRunner.Then("I select the AM acid with exposure unit as mg", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 47
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AmmoniaMethyla" +
                    "mine Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 49
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.And("After setting up the environment details for AmmoniaMethylamine Acid Mixture_mg3 " +
                    "click on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.Then("Verify the Service Life Estimate for AmmoniaMethylamine Acid Mixture_mg3 and then" +
                    " click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06 Acid Validations AmmoniaMethylamine_mg3")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _06AcidValidationsAmmoniaMethylamine_Mg3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 Acid Validations AmmoniaMethylamine_mg3", null, new string[] {
                        "regression"});
#line 54
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 55
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.Then("I select the AM acid with exposure unit as mg3", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 57
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AmmoniaMethyla" +
                    "mine Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 59
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.And("After setting up the environment details for AmmoniaMethylamine Acid MixtureMg cl" +
                    "ick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.Then("Verify the Service Life Estimate for AmmoniaMethylamine Acid MixtureMg and then c" +
                    "lick on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07 Acid Validations AmmoniaSO2_ppm")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _07AcidValidationsAmmoniaSO2_Ppm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 Acid Validations AmmoniaSO2_ppm", null, new string[] {
                        "regression"});
#line 64
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 65
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 66
 testRunner.Then("I select the ASO2 acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 67
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 68
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for ASO2 Acid Mixt" +
                    "ure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 69
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.And("After setting up the environment details for ASO2 Acid Mixture click on next butt" +
                    "on to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.Then("Verify the Service Life Estimate for ASO2 Acid Mixture and then click on Done but" +
                    "ton to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08 Acid Validations H2SSO2")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _08AcidValidationsH2SSO2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 Acid Validations H2SSO2", null, new string[] {
                        "regression"});
#line 74
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 75
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 76
 testRunner.Then("I select the H2SSO2 acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 77
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for H2SSO2 Acid Mi" +
                    "xture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 79
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.And("After setting up the environment details for H2SSO2 Acid Mixture click on next bu" +
                    "tton to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.Then("Verify the Service Life Estimate for H2SSO2 Acid Mixture and then click on Done b" +
                    "utton to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("09 Acid Validations AcetoneSO2")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _09AcidValidationsAcetoneSO2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("09 Acid Validations AcetoneSO2", null, new string[] {
                        "regression"});
#line 83
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 84
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.Then("I select the AcetoneSO2 acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AcetoneSO2 Aci" +
                    "d Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 88
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And("After setting up the environment details for AcetoneSO2 Acid Mixture click on nex" +
                    "t button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.Then("Verify the Service Life Estimate for AcetoneSO2 Acid Mixture and then click on Do" +
                    "ne button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("10 Acid Validations TouleneAmmonia_ppm")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _10AcidValidationsTouleneAmmonia_Ppm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 Acid Validations TouleneAmmonia_ppm", null, new string[] {
                        "regression"});
#line 92
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 93
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 94
 testRunner.Then("I select the TouleneAmmonia acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneAmmonia" +
                    " Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 97
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
 testRunner.And("After setting up the environment details for TouleneAmmonia Acid Mixture click on" +
                    " next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.Then("Verify the Service Life Estimate for TouleneAmmonia Acid Mixture and then click o" +
                    "n Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11 Acid Validations TouleneAmmonia(mg3)")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _11AcidValidationsTouleneAmmoniaMg3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11 Acid Validations TouleneAmmonia(mg3)", null, new string[] {
                        "regression"});
#line 101
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 102
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 103
 testRunner.Then("I select the TouleneAmmonia2 acids", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneAmmonia" +
                    " Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 107
 testRunner.And("After setting up the environment details for TouleneAmmonia Acid Mixture click on" +
                    " next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.Then("Verify the Service Life Estimate for TouleneAmmonia2 Acid Mixture and then click " +
                    "on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12 Acid Validations AmmoniaSulfurDioxide")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _12AcidValidationsAmmoniaSulfurDioxide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12 Acid Validations AmmoniaSulfurDioxide", null, new string[] {
                        "regression"});
#line 110
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 111
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 112
 testRunner.Then("I select the AmmoniaSulfurDioxide acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 114
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AmmoniaSulfurD" +
                    "ioxide Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 115
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 116
 testRunner.And("After setting up the environment details for AmmoniaSulfurDioxide Acid Mixture cl" +
                    "ick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.Then("Verify the Service Life Estimate for AmmoniaSulfurDioxide Acid Mixture and then c" +
                    "lick on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13 Acid Validations AmmoniaSulfurDioxide")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _13AcidValidationsAmmoniaSulfurDioxide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13 Acid Validations AmmoniaSulfurDioxide", null, new string[] {
                        "regression"});
#line 119
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 120
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 121
 testRunner.Then("I select the AmmoniaSulfurDioxide1 acids", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 122
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AmmoniaSulfurD" +
                    "ioxide Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 124
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 125
 testRunner.And("After setting up the environment details for AmmoniaSulfurDioxide Acid Mixture cl" +
                    "ick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
 testRunner.Then("Verify the Service Life Estimate for AmmoniaSulfurDioxide1 Acid Mixture and then " +
                    "click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14 Acid Validations TouleneSulfurDioxide")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _14AcidValidationsTouleneSulfurDioxide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14 Acid Validations TouleneSulfurDioxide", null, new string[] {
                        "regression"});
#line 128
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 129
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 130
 testRunner.Then("I select the TouleneSulfurDioxide acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 131
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneSulfurD" +
                    "ioxide Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 133
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 134
 testRunner.And("After setting up the environment details for TouleneSulfurDioxide Acid Mixture cl" +
                    "ick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.Then("Verify the Service Life Estimate for TouleneSulfurDioxide Acid Mixture and then c" +
                    "lick on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("15 Acid Validations TouleneSulfurDioxide1")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _15AcidValidationsTouleneSulfurDioxide1()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("15 Acid Validations TouleneSulfurDioxide1", null, new string[] {
                        "regression"});
#line 137
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 138
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 139
 testRunner.Then("I select the TouleneSulfurDioxide acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneSulfurD" +
                    "ioxide Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 142
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
 testRunner.And("After setting up the environment details for TouleneSulfurDioxide1 Acid Mixture c" +
                    "lick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.Then("Verify the Service Life Estimate for TouleneSulfurDioxide1 Acid Mixture and then " +
                    "click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("16 Acid Validations AcetonitrileMethylineChlorideFormamide")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _16AcidValidationsAcetonitrileMethylineChlorideFormamide()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("16 Acid Validations AcetonitrileMethylineChlorideFormamide", null, new string[] {
                        "regression"});
#line 155
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 156
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 157
 testRunner.Then("I select the AcetonitrileMethylineChlorideFormamide acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 158
 testRunner.And("I click on next button and then click on Done button on Refine Result for Acetoni" +
                    "trileMethylineChlorideFormamide", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AcetonitrileMe" +
                    "thylineChlorideFormamide Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 160
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 161
 testRunner.And("After setting up the environment details for AcetonitrileMethylineChlorideFormami" +
                    "de Acid Mixture click on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.Then("Verify the Service Life Estimate for AcetonitrileMethylineChlorideFormamide Acid " +
                    "Mixture and then click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("17 Acid Validations TouleneSOAmmonia")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _17AcidValidationsTouleneSOAmmonia()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("17 Acid Validations TouleneSOAmmonia", null, new string[] {
                        "regression"});
#line 164
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 165
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 166
 testRunner.Then("I select the TouleneSOAmmonia acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 167
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneSOAmmon" +
                    "ia Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 169
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 170
 testRunner.And("After setting up the environment details for TouleneSOAmmonia Acid Mixture click " +
                    "on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 171
 testRunner.Then("Verify the Service Life Estimate for TouleneSOAmmonia Acid Mixture and then click" +
                    " on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("18 Acid Validations TouleneHexSO2HF")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _18AcidValidationsTouleneHexSO2HF()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("18 Acid Validations TouleneHexSO2HF", null, new string[] {
                        "regression"});
#line 173
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 174
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 175
 testRunner.Then("I select the TouleneHexSO2HF acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 176
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneHexSO2H" +
                    "F Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 178
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 179
 testRunner.And("After setting up the environment details for TouleneHexSO2HF Acid Mixture click o" +
                    "n next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.Then("Verify the Service Life Estimate for TouleneHexSO2HF Acid Mixture and then click " +
                    "on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("19 Acid Validations TouleneHexSO2HF")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _19AcidValidationsTouleneHexSO2HF()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("19 Acid Validations TouleneHexSO2HF", null, new string[] {
                        "regression"});
#line 182
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 183
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 184
 testRunner.Then("I select the TouleneHexSO2HF2 acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 185
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 186
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneHexSO2H" +
                    "F Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 187
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 188
 testRunner.And("After setting up the environment details for TouleneHexSO2HF2 Acid Mixture click " +
                    "on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 189
 testRunner.Then("Verify the Service Life Estimate for TouleneHexSO2HF2 Acid Mixture and then click" +
                    " on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("20 Acid Validations TouleneHexAmmoniaMeth")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _20AcidValidationsTouleneHexAmmoniaMeth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("20 Acid Validations TouleneHexAmmoniaMeth", null, new string[] {
                        "regression"});
#line 191
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 192
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 193
 testRunner.Then("I select the TouleneHexAmmoniaMeth acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 194
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 195
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneHexAmmo" +
                    "niaMeth Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 196
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 197
 testRunner.And("After setting up the environment details for TouleneHexAmmoniaMeth Acid Mixture c" +
                    "lick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 198
 testRunner.Then("Verify the Service Life Estimate for TouleneHexAmmoniaMeth Acid Mixture and then " +
                    "click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21 Acid Validations SulphurHFAmmoniaMeth")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _21AcidValidationsSulphurHFAmmoniaMeth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21 Acid Validations SulphurHFAmmoniaMeth", null, new string[] {
                        "regression"});
#line 200
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 201
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 202
 testRunner.Then("I select the SulphurHFAmmoniaMeth acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 203
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for SulphurHFAmmon" +
                    "iaMeth Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 205
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 206
 testRunner.And("After setting up the environment details for SulphurHFAmmoniaMeth Acid Mixture cl" +
                    "ick on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 207
 testRunner.Then("Verify the Service Life Estimate for SulphurHFAmmoniaMeth Acid Mixture and then c" +
                    "lick on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22 Acid Validations TouleneAceticMEKXylene")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _22AcidValidationsTouleneAceticMEKXylene()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22 Acid Validations TouleneAceticMEKXylene", null, new string[] {
                        "regression"});
#line 209
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 210
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 211
 testRunner.Then("I select the TouleneAceticMEKXylene acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 212
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneAceticM" +
                    "EKXylene Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 214
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 215
 testRunner.And("After setting up the environment details for TouleneAceticMEKXylene Acid Mixture " +
                    "click on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.Then("Verify the Service Life Estimate for TouleneAceticMEKXylene Acid Mixture and then" +
                    " click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23 Acid Validations TouleneAceticMEKXylene2")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _23AcidValidationsTouleneAceticMEKXylene2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23 Acid Validations TouleneAceticMEKXylene2", null, new string[] {
                        "regression"});
#line 218
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 219
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 220
 testRunner.Then("I select the TouleneAceticMEKXylene2 acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 221
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 222
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneAceticM" +
                    "EKXylene Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 223
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 224
 testRunner.And("After setting up the environment details for TouleneAceticMEKXylene2 Acid Mixture" +
                    " click on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.Then("Verify the Service Life Estimate for TouleneAceticMEKXylene2 Acid Mixture and the" +
                    "n click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24 Acid Validations AmmoniaHFHSSO2Methy")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _24AcidValidationsAmmoniaHFHSSO2Methy()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24 Acid Validations AmmoniaHFHSSO2Methy", null, new string[] {
                        "regression"});
#line 227
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 228
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 229
 testRunner.Then("I select the AmmoniaHFHSSO2Methy acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 230
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 231
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for AmmoniaHFHSSO2" +
                    "Methy Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 232
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 233
 testRunner.And("After setting up the environment details for AmmoniaHFHSSO2Methy Acid Mixture cli" +
                    "ck on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
 testRunner.Then("Verify the Service Life Estimate for AmmoniaHFHSSO2Methy Acid Mixture and then cl" +
                    "ick on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("25 Acid Validations TouleneHexaneSO2HFAmmoniaMethylamine")]
        [NUnit.Framework.CategoryAttribute("regression")]
        public virtual void _25AcidValidationsTouleneHexaneSO2HFAmmoniaMethylamine()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("25 Acid Validations TouleneHexaneSO2HFAmmoniaMethylamine", null, new string[] {
                        "regression"});
#line 236
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 237
 testRunner.Given("I have already navigated to the SLS WebPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 238
 testRunner.Then("I select the TouleneHexaneSO2HFAmmoniaMethylamine acid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 239
 testRunner.And("I click on next button and then click on Done button on Refine Result", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
 testRunner.Then("I filter the required cartidge/filter using the cartidge value for TouleneHexaneS" +
                    "O2HFAmmoniaMethylamine Acid Mixture", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 241
 testRunner.When("I click on the Select And Continue button , I should be in environment setup page" +
                    ".", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 242
 testRunner.And("After setting up the environment details for TouleneHexaneSO2HFAmmoniaMethylamine" +
                    " Acid Mixture click on next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 243
 testRunner.Then("Verify the Service Life Estimate for TouleneHexaneSO2HFAmmoniaMethylamine Acid Mi" +
                    "xture and then click on Done button to complete the verification process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
