// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SalemWeb.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CreateOrganisation")]
    public partial class CreateOrganisationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateOrganisation.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateOrganisation", "\tCreating new Organisation", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Create a new Organisation")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("NCOrgTestQA01", "India", "Jharkhand", "Ranchi", "3M Scott", "Fire Department", "Fire Services", "Active", "NCTest01", "QA01", "NCTestQA01@test.com", "1234567891", new string[] {
                "source:OrganisationCreateData.xlsx"}, Category="source:OrganisationCreateData.xlsx")]
        [NUnit.Framework.TestCaseAttribute("NCOrgTestQA02", "India", "Jharkhand", "Ranchi", "3M Scott", "Fire Department", "Fire Services", "Active", "NCTest02", "QA02", "NCTestQA02@test.com", "1234567892", new string[] {
                "source:OrganisationCreateData.xlsx"}, Category="source:OrganisationCreateData.xlsx")]
        [NUnit.Framework.TestCaseAttribute("NCOrgTestQA03", "India", "Jharkhand", "Ranchi", "3M Scott", "Fire Department", "Fire Services", "Active", "NCTest03", "QA03", "NCTestQA03@test.com", "1234567893", new string[] {
                "source:OrganisationCreateData.xlsx"}, Category="source:OrganisationCreateData.xlsx")]
        public virtual void CreateANewOrganisation(string orgName, string country, string state, string city, string bussiness_Unit, string account_Type, string field, string status, string firstName, string lastName, string email, string contactNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Create a new Organisation", null, @__tags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
testRunner.Given("I have a valid url and navigated to the url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
testRunner.Then("I click on the Sign In button to go to User Sign In portal.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
testRunner.When("Redirected to the login portal, enter your valid username and password.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
testRunner.And("Click on Sign In button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
testRunner.Then("Verify if Login is successfull.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 11
testRunner.And("Select the users organistion.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
testRunner.Then("Click on continue button to finish with the login process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
testRunner.And("Click on the Organisations link to redirect to Organisation DashBoard.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
testRunner.Then("In the Organisation Dashboard, tap on the CreateNewOrganisation button to proceed" +
                    " with the new organisation creation.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
testRunner.When(string.Format("Redirected to the CreateOrganistion dashboard, fill the necessary details such as" +
                        " {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11}", orgName, firstName, country, lastName, state, email, city, contactNumber, bussiness_Unit, account_Type, field, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
testRunner.Then("Click on Create button to complete with the Organisation creation.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
testRunner.And("Verify that new Organisation is created successfully or not.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
testRunner.And("click on logout button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Cancel Button Validation")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("NCOrgTestQA01", "India", "Jharkhand", "Ranchi", "3M Scott", "Fire Department", "Fire Services", "Active", "NCTest01", "QA01", "NCTestQA01@test.com", "1234567891", new string[] {
                "source:OrganisationCreateData.xlsx"}, Category="source:OrganisationCreateData.xlsx")]
        [NUnit.Framework.TestCaseAttribute("NCOrgTestQA02", "India", "Jharkhand", "Ranchi", "3M Scott", "Fire Department", "Fire Services", "Active", "NCTest02", "QA02", "NCTestQA02@test.com", "1234567892", new string[] {
                "source:OrganisationCreateData.xlsx"}, Category="source:OrganisationCreateData.xlsx")]
        [NUnit.Framework.TestCaseAttribute("NCOrgTestQA03", "India", "Jharkhand", "Ranchi", "3M Scott", "Fire Department", "Fire Services", "Active", "NCTest03", "QA03", "NCTestQA03@test.com", "1234567893", new string[] {
                "source:OrganisationCreateData.xlsx"}, Category="source:OrganisationCreateData.xlsx")]
        public virtual void CancelButtonValidation(string orgName, string country, string state, string city, string bussiness_Unit, string account_Type, string field, string status, string firstName, string lastName, string email, string contactNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cancel Button Validation", null, @__tags);
#line 24
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 25
testRunner.Given("I have a valid url and navigated to the url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 26
testRunner.Then("I click on the Sign In button to go to User Sign In portal.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 27
testRunner.When("Redirected to the login portal, enter your valid username and password.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
testRunner.And("Click on Sign In button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
testRunner.Then("Verify if Login is successfull.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
testRunner.And("Select the users organistion.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
testRunner.Then("Click on continue button to finish with the login process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
testRunner.And("Click on the Organisations link to redirect to Organisation DashBoard.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
testRunner.Then("In the Organisation Dashboard, tap on the CreateNewOrganisation button to proceed" +
                    " with the new organisation creation.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 34
testRunner.When(string.Format("Redirected to the CreateOrganistion dashboard, fill the necessary details such as" +
                        " {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11}", orgName, firstName, country, lastName, state, email, city, contactNumber, bussiness_Unit, account_Type, field, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
testRunner.Then("Click on Cancel Button and verify if Organization creation is canceled successful" +
                    "ly.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
testRunner.And("click on logout button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Required Feild Validation.")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("", "India", "Jharkhand", "Ranchi", "", "", "", "", "", "", "", "", new string[] {
                "source:EmptyFields.xlsx"}, Category="source:EmptyFields.xlsx")]
        public virtual void RequiredFeildValidation_(string orgName, string country, string state, string city, string bussiness_Unit, string account_Type, string field, string status, string firstName, string lastName, string email, string contactNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Required Feild Validation.", null, @__tags);
#line 42
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 43
testRunner.Given("I have a valid url and navigated to the url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 44
testRunner.Then("I click on the Sign In button to go to User Sign In portal.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
testRunner.When("Redirected to the login portal, enter your valid username and password.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
testRunner.And("Click on Sign In button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
testRunner.Then("Verify if Login is successfull.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
testRunner.And("Select the users organistion.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
testRunner.Then("Click on continue button to finish with the login process.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 50
testRunner.And("Click on the Organisations link to redirect to Organisation DashBoard.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
testRunner.Then("In the Organisation Dashboard, tap on the CreateNewOrganisation button to proceed" +
                    " with the new organisation creation.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
testRunner.When(string.Format("Redirected to the CreateOrganistion dashboard, fill the necessary details such as" +
                        " {0},{1},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11}", orgName, firstName, country, lastName, state, email, city, contactNumber, bussiness_Unit, account_Type, field, status), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 53
testRunner.Then("Click on Create button to complete with the Organisation creation.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
testRunner.And("Verify that no new Organisation is created successfully or not.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
testRunner.And("click on logout button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
