// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SalemWeb.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PostOrganisationCreation")]
    public partial class PostOrganisationCreationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PostOrganisationCreation.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PostOrganisationCreation", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Adding user to Organisation")]
        [NUnit.Framework.CategoryAttribute("regressiontest")]
        [NUnit.Framework.TestCaseAttribute("srani.cw@mmm.com", "Summer#2020", "3M Internal Group", "OrgkritiNC1234", " Application User", "kriti1", "shri", "ksa1as@gmail.com", "6789", " Application User", new string[] {
                "source:PostOrganisationCreation.xlsx:AddUser"}, Category="source:PostOrganisationCreation.xlsx:AddUser")]
        public virtual void AddingUserToOrganisation(string email, string password, string organisation, string orgName, string role, string fName, string lName, string emailID, string num, string @string, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regressiontest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding user to Organisation", null, @__tags);
#line 4
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
 testRunner.Given("Navigate to url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
    testRunner.Then("Click on Sign In button to proceed with approving software request.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.And(string.Format("After landing on sign in page. Enter email {0} and {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.Then("Click on Sign in button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.And(string.Format("select organisation {0} from dropdown menu and click on Continue button.", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("After landing on website, click on organisation button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And(string.Format("enter organisation name {0} in searchbox.", orgName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
testRunner.And("Click on add user button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.Then(string.Format("After landing on user page, select user role {0} , enter firstname {1}, lastname " +
                        "{2}, emailid{3}, contact number{4}.", role, fName, lName, emailID, num), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And(string.Format("Click on Create Button to create new user for an organisation and specify all str" +
                        "ing {0}", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("verify user creation.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Deleting an Organisation")]
        [NUnit.Framework.CategoryAttribute("reGressionTest")]
        [NUnit.Framework.TestCaseAttribute("srani.cw@mmm.com", "Summer#2020", "3M Internal Group", "orgtodeletenathcorp", new string[] {
                "source:PostOrganisationCreation.xlsx:DeleteOrg"}, Category="source:PostOrganisationCreation.xlsx:DeleteOrg")]
        public virtual void DeletingAnOrganisation(string email, string password, string organisation, string orgName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "reGressionTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deleting an Organisation", null, @__tags);
#line 25
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 26
testRunner.Given("Navigate to url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
    testRunner.Then("Click on Sign In button to proceed with approving software request.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 28
 testRunner.And(string.Format("After landing on sign in page. Enter email {0} and {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.Then("Click on Sign in button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 30
 testRunner.And(string.Format("select organisation {0} from dropdown menu and click on Continue button.", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
  testRunner.When("After landing on website, click on organisation button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.And(string.Format("enter organisation name {0} in searchbox.", orgName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.Then("Click on delete.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 37
 testRunner.And("Verify deletion of user.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Send Email")]
        [NUnit.Framework.CategoryAttribute("reGRessionTest")]
        [NUnit.Framework.TestCaseAttribute("srani.cw@mmm.com", "Summer#2020", "3M Internal Group", "OrgkritiNC123", new string[] {
                "source:PostOrganisationCreation.xlsx:SendEmail"}, Category="source:PostOrganisationCreation.xlsx:SendEmail")]
        public virtual void SendEmail(string email, string password, string organisation, string orgName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "reGRessionTest"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send Email", null, @__tags);
#line 43
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 44
 testRunner.Given("Navigate to url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
    testRunner.Then("Click on Sign In button to proceed with approving software request.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.And(string.Format("After landing on sign in page. Enter email {0} and {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.Then("Click on Sign in button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 48
 testRunner.And(string.Format("select organisation {0} from dropdown menu and click on Continue button.", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
  testRunner.When("After landing on website, click on organisation button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.And(string.Format("enter organisation name {0} in searchbox.", orgName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.Then("click on email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 54
 testRunner.And("verify email sent.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add role to user")]
        [NUnit.Framework.CategoryAttribute("reGressionTEST")]
        [NUnit.Framework.TestCaseAttribute("srani.cw@mmm.com", "Summer#2020", "3M Internal Group", "usernathcorp", new string[] {
                "source:PostOrganisationCreation.xlsx:AddRole"}, Category="source:PostOrganisationCreation.xlsx:AddRole")]
        public virtual void AddRoleToUser(string email, string password, string organisation, string userName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "reGressionTEST"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add role to user", null, @__tags);
#line 60
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 61
 testRunner.Given("Navigate to url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
    testRunner.Then("Click on Sign In button to proceed with approving software request.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
 testRunner.And(string.Format("After landing on sign in page. Enter email {0} and {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.Then("Click on Sign in button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 65
 testRunner.And(string.Format("select organisation {0} from dropdown menu and click on Continue button.", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.When("after landing on website, click on user button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.And(string.Format("enter user name {0} in searchbox", userName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.Then("select user role , Business Unit and Organisation from dropdownmenu.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 73
 testRunner.And("click on add role button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("Verify role addition", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Remove role from user")]
        [NUnit.Framework.CategoryAttribute("reGressionTEst")]
        [NUnit.Framework.TestCaseAttribute("srani.cw@mmm.com", "Summer#2020", "3M Internal Group", "kriti", new string[] {
                "source:PostOrganisationCreation.xlsx:RemoveRole"}, Category="source:PostOrganisationCreation.xlsx:RemoveRole")]
        public virtual void RemoveRoleFromUser(string email, string password, string organisation, string userName, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "reGressionTEst"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Remove role from user", null, @__tags);
#line 81
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 82
 testRunner.Given("Navigate to url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
    testRunner.Then("Click on Sign In button to proceed with approving software request.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 84
 testRunner.And(string.Format("After landing on sign in page. Enter email {0} and {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.Then("Click on Sign in button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 86
 testRunner.And(string.Format("select organisation {0} from dropdown menu and click on Continue button.", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.When("after landing on website, click on user button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
 testRunner.And(string.Format("enter user name {0} in searchbox", userName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("scroll down to remove role button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.Then("Click on confirm button to remove role.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 95
 testRunner.And("verify removal of role.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Edit user")]
        [NUnit.Framework.CategoryAttribute("reGressiONTEST")]
        [NUnit.Framework.TestCaseAttribute("srani.cw@mmm.com", "Summer#2020", "3M Internal Group", "kriti", "", new string[] {
                "source:PostOrganisationCreation.xlsx:EditUser"}, Category="source:PostOrganisationCreation.xlsx:EditUser")]
        public virtual void EditUser(string email, string password, string organisation, string userName, string num, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "reGressiONTEST"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Edit user", null, @__tags);
#line 101
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 102
 testRunner.Given("Navigate to url.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 103
    testRunner.Then("Click on Sign In button to proceed with approving software request.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And(string.Format("After landing on sign in page. Enter email {0} and {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.Then("Click on Sign in button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 106
 testRunner.And(string.Format("select organisation {0} from dropdown menu and click on Continue button.", organisation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.When("after landing on website, click on user button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 110
 testRunner.And(string.Format("enter user name {0} in searchbox", userName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.Then("click on edit button to edit user.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 114
 testRunner.And("click save.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.And("verify user edit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
