// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ServiceLifeChile.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ValidatingServiceLifeHours")]
    public partial class ValidatingServiceLifeHoursFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ValidatingServiceLifeHours.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ValidatingServiceLifeHours", "\tValidating the Hours for the Cartidges", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Service Life Hours Validation.")]
        [NUnit.Framework.TestCaseAttribute("1", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "20", "Celsius", "Medium", "34 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("2", "Tolueno", "108-88-3", "100", "ppm", "60921", "<65%", "1", "20", "Celsius", "Medium", "34 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("3", "Tolueno", "108-88-3", "383.28", "mg/m3 ", "6001", "<65%", "1", "20", "Celsius", "Medium", "34 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("4", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "0", "Celsius", "Medium", "37 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("5", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "10", "Celsius", "Medium", "36 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("6", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "30", "Celsius", "Medium", "31 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("7", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "40", "Celsius", "Medium", "29 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("8", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "50", "Celsius", "Medium", "26 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("9", "Tolueno", "108-88-3", "100", "ppm", "6003", "<65%", "1", "20", "Celsius", "Medium", "29 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("10", "Tolueno", "108-88-3", "100", "ppm", "60923", "<65%", "1", "20", "Celsius", "Medium", "29 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("11", "Tolueno", "108-88-3", "100", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "24 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("12", "Tolueno", "108-88-3", "100", "ppm", "60926", "<65%", "1", "20", "Celsius", "Medium", "24 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("13", "Tolueno", "108-88-3", "100", "ppm", "6007", "<65%", "1", "20", "Celsius", "Medium", "31 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("14", "Tolueno", "108-88-3", "100", "ppm", "60927", "<65%", "1", "20", "Celsius", "Medium", "31 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("15", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "20", "Celsius", "Light", "67 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("16", "Tolueno", "108-88-3", "100", "ppm", "6001", "<65%", "1", "20", "Celsius", "Heavy", "22 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("17", "Tolueno", "108-88-3", "100", "ppm", "TR-6110E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "29 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("18", "Tolueno", "108-88-3", "100", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "27 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("19", "Tolueno", "108-88-3", "100", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Tight fitting - medium airflow", "24 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("20", "Tolueno", "108-88-3", "100", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Tight fitting - high airflow", "21 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("21", "Tolueno", "108-88-3", "100", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Loose fitting - standard airflow", "19 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("22", "Tolueno", "108-88-3", "100", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Loose fitting - medium airflow", "18 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("23", "Tolueno", "108-88-3", "100", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Loose fitting - high airflow", "17 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("24", "Tolueno", "108-88-3", "100", "ppm", "TR-6310E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "40 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("25", "Tolueno", "108-88-3", "100", "ppm", "TR-6580E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "34 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("26", "Benceno", "71-43-2", "0.4", "ppm", "6003", "<65%", "1", "30", "Celsius", "Medium", "669 horas", "0.8", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("27", "Xileno (o-, m-, p-isómeros)", "1330-20-7", "50", "ppm", "6001", "<65%", "0.8", "20", "Celsius", "Medium", "78 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("28", "Xileno (o-, m-, p-isómeros)", "1330-20-7", "50", "ppm", "6001", "<65%", "1", "20", "Celsius", "Medium", "64 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("29", "Xileno (o-, m-, p-isómeros)", "1330-20-7", "50", "ppm", "6001", "<65%", "1.2", "20", "Celsius", "Medium", "54 horas", "87", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("30", "Hexano (n-hexano)", "110-54-3", "10", "ppm", "6001", "<65%", "1", "20", "Celsius", "Medium", "110 horas", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("31", "Hexano (n-hexano)", "110-54-3", "10", "ppm", "6001", "65", "1", "20", "Celsius", "Medium", "42 horas", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("32", "Hexano (n-hexano)", "110-54-3", "10", "ppm", "6001", "75", "1", "20", "Celsius", "Medium", "19 horas", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("33", "Hexano (n-hexano)", "110-54-3", "10", "ppm", "6001", "85", "1", "20", "Celsius", "Medium", "13 horas", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("34", "Hexano (n-hexano)", "110-54-3", "10", "ppm", "6001", "90", "1", "20", "Celsius", "Medium", "11 horas", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("35", "Hexano (n-hexano)", "110-54-3", "1", "ppm", "6001", "<65%", "1", "50", "Celsius", "Medium", "257 horas", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("36", "Hexano (n-hexano)", "110-54-3", "1", "ppm", "6001", "85", "1", "50", "Celsius", "Medium", "440 minutos", "20", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("37", "Divinil benceno", "1321-74-0", "100", "ppm", "6001", "<65%", "1", "0", "Celsius", "Medium", "33 horas", "10", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("38", "Divinil benceno", "1321-74-0", "100", "ppm", "6001", "85", "1", "0", "Celsius", "Medium", "33 horas", "10", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("39", "Amoniaco", "7664-41-7", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Light", "19 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("40", "Amoniaco", "7664-41-7", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "9 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("41", "Amoniaco", "7664-41-7", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Heavy", "370 minutos", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("42", "Amoniaco", "7664-41-7", "30", "ppm", "6004", "<65%", "1", "20", "Celsius", "Medium", "77 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("43", "Amoniaco", "7664-41-7", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "9 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("44", "Amoniaco", "7664-41-7", "20.55", "mg/m3 ", "6004", "<65%", "1", "30", "Celsius", "Medium", "77 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("45", "Amoniaco", "7664-41-7", "30", "ppm", "6004", "85", "0.95", "30", "Celsius", "Heavy", "51 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("46", "Amoniaco", "7664-41-7", "30", "ppm", "TR-6580E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "29 horas", "21.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("47", "Cianógeno", "460-19-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "42 horas", "5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("48", "Cloro", "7782-50-5", "30", "ppm", "6003", "<65%", "1", "20", "Celsius", "Medium", "65 horas", "0.45", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("49", "Cloro", "7782-50-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "200 horas", "0.45", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("50", "Formaldehído", "50-00-0", "30", "ppm", "6005", "<65%", "1", "20", "Celsius", "Medium", "366 minutos", "0.1", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("51", "Formaldehído", "50-00-0", "30", "ppm", "TR-6580E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "121 minutos", "0.1", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("52", "HF", "7664-39-3", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Light", "253 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("53", "HF", "7664-39-3", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "126 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("54", "HF", "7664-39-3", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Heavy", "84 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("55", "HF", "7664-39-3", "30", "ppm", "6002", "<65%", "1", "20", "Celsius", "Medium", "154 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("56", "HF", "7664-39-3", "30", "ppm", "6003", "<65%", "1", "20", "Celsius", "Medium", "71 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("57", "HF", "7664-39-3", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "126 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("58", "HF", "7664-39-3", "30", "ppm", "7093C", "<65%", "1", "20", "Celsius", "Medium", "8 horas", "0.5", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("59", "H2S", "7783-06-4", "30", "ppm", "6002", "<65%", "1", "20", "Celsius", "Medium", "1428 horas", "8.8", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("60", "H2S", "7783-06-4", "30", "ppm", "6003", "<65%", "1", "20", "Celsius", "Medium", "760 horas", "8.8", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("61", "H2S", "7783-06-4", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "679 horas", "8.8", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("62", "H2S", "7783-06-4", "30", "ppm", "6007", "<65%", "1", "20", "Celsius", "Medium", "142 horas", "8.8", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("63", "Metilamina", "74-89-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Light", "89 horas", "4.4", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("64", "Metilamina", "74-89-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "45 horas", "4.4", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("65", "Metilamina", "74-89-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Heavy", "30 horas", "4.4", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("66", "Metilamina", "74-89-5", "30", "ppm", "6004", "<65%", "1", "20", "Celsius", "Medium", "245 horas", "4.4", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("67", "Metilamina", "74-89-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "45 horas", "4.4", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("68", "SO2", "7446-09-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Light", "88 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("69", "SO2", "7446-09-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "44 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("70", "SO2", "7446-09-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Heavy", "29 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("71", "SO2", "7446-09-5", "30", "ppm", "6002", "<65%", "1", "20", "Celsius", "Medium", "164 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("72", "SO2", "7446-09-5", "30", "ppm", "6003", "<65%", "1", "20", "Celsius", "Medium", "46 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("73", "SO2", "7446-09-5", "30", "ppm", "6006", "<65%", "1", "20", "Celsius", "Medium", "44 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("74", "SO2", "7446-09-5", "30", "ppm", "6007", "<65%", "1", "20", "Celsius", "Medium", "400 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("75", "SO2", "7446-09-5", "15", "ppm", "6003", "<65%", "1", "30", "Celsius", "Light", "222 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("76", "SO2", "7446-09-5", "79.9", "mg/m3 ", "6002", "<65%", "1", "20", "Celsius", "Medium", "164 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("77", "SO2", "7446-09-5", "30", "ppm", "TR-6130E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "42 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("78", "SO2", "7446-09-5", "30", "ppm", "TR-6580E", "<65%", "1", "20", "Celsius", "Tight fitting - standard airflow", "129 horas", "1.7", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        [NUnit.Framework.TestCaseAttribute("79", "2-Propanol", "67-63-0", "1.87", "ppm", "6006", "65", "1", "20", "Celsius", "Medium", "247 minutos", "350", "ppm", "Chile", new string[] {
                "source:Servicelife_Testcases_Chile.xlsx:main"}, Category="source:Servicelife_Testcases_Chile.xlsx:main")]
        public virtual void ServiceLifeHoursValidation_(
                    string s_No, 
                    string contaminate, 
                    string cas_Number, 
                    string exposure, 
                    string exposure_Unit, 
                    string cartridge, 
                    string relative_Humidity, 
                    string atmospheric_Pressure, 
                    string temperature, 
                    string temperature_Unit, 
                    string work_Rate, 
                    string hours, 
                    string exposure_Limit, 
                    string exposure_Limit_Unit, 
                    string region, 
                    string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Service Life Hours Validation.", null, exampleTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
testRunner.Given("I have navigated to SLS Web Application.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
testRunner.Then(string.Format("I set region as {0} from sheet.", region), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
testRunner.And("I click on the next button to proceed further.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
testRunner.Then("In the Setup page I select the Service Life result and click on IAccept to contin" +
                    "ue.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
testRunner.And(string.Format("In the contaminant page I filter the Contaminants using {0} and set the {1} and {" +
                        "2}", cas_Number, exposure, exposure_Unit), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
testRunner.And("In the refine page I click on done button.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
testRunner.Then(string.Format("In the filter page select the solution {0} that works for you.", cartridge), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
testRunner.And(string.Format("In Environment page I set the details of {0},{1},{2},{3} and {4}", relative_Humidity, atmospheric_Pressure, temperature, temperature_Unit, work_Rate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
testRunner.Then(string.Format("I verify the {0} in the review page.", hours), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
