// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SelectFrance.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SelectFrance")]
    public partial class SelectFranceFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SelectFrance.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SelectFrance", "     Validate the total cartidges for the below scenarios.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate the Cartidges.")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("1", "N", "Dioxyde d\'azote", "10102-44-0", "AA", "", "", "", "", "", "", "", "", "", "", "0", @"3M n'a pas de filtre approprié pour un ou plusieurs de vos contaminants. Les respirateurs à adduction d'air peuvent être appropriés pour aider à réduire l'exposition en fonction du facteur de protection du respirateur choisi. Veuillez consulter les « Ressources » ci-dessous ou contactez le + 33 (0)1 30 31 65 96 pour plus d'informations.", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("2", "N", "Talc non fibreux", "14807-96-6", "P1", "", "", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "", "2135, 6035, D3135, D9035, 2125, D3125", "TR-3712E, TR-6710E", "8833, \n8835+, \n9330,\n9332+,\n8825+,\n9320+, \n9322+, \n9310+, \n9312+,\n2135, \n6035, \nD" +
            "3135, \nD9035, \n2125, \nD3125,\nTR-3712E, \nTR-6710E,\nDT-1135E", "18", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("3", "N", "Talc non fibreux", "14807-96-6", "P1", "Yes", "", "", "", "", "9936, 9922, 9925, 9928, 9926, 9913, 9914", "", "6038, 2138, D3138, 2128, D3128", "TR-3822E, TR-3802E, TR-6820E", "9936, \n9922, \n9925, \n9928, \n9926, \n9913, \n9914,\n6038, \n2138, \nD3138,\n 2128, \nD312" +
            "8,\nTR-3822E,\n TR-3802E, \nTR-6820E", "15", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("4", "N", "Talc non fibreux", "14807-96-6", "P1", "No", "", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "", "2135, 6035, D3135, D9035, 2125, D3125", "TR-3712E, TR-6710E", "8833,\n 8835+,\n 9330,\n 9332+,\n 8825+,\n 9320+,\n 9322+, \n9310+, \n9312+,\n2135,\n 6035," +
            " \nD3135, \nD9035, \n2125, \nD3125,\nTR-3712E, \nTR-6710E,\nDT-1135E", "18", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("5", "N", "Talc non fibreux", "14807-96-6", "P1", "No", "", "Disposable", "", "", "8833, 8835+, 9330+, 9332+, 8825+, 9320+, 9322+, 9310+, 9312+", "", "", "", "8833,\n 8835+,\n 9330+,\n 9332+,\n 8825+,\n 9320+,\n 9322+, \n9310+, \n9312+", "9", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("6", "N", "Talc non fibreux", "14807-96-6", "P1", "No", "", "Reusable", "", "", "", "", "2135, 6035, D3135, D9035, 2125, D3125", "", "2135,\n 6035,\n D3135,\n D9035,\n 2125, \nD3125,\nDT-1135E", "7", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("7", "N", "Talc non fibreux", "14807-96-6", "P1", "No", "", "PAPR", "", "", "", "", "", "TR-3712E, TR-6710E", "TR-3712E, TR-6710E,DT-1135E", "3", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("8", "N", "Perchlorobenzène", "118-74-1", "P2", "", "", "", "", "", "8833, 8835+, 9330, 9332+, 8825+, 9320+, 9322+", "", "2135, 6035, D3135, D9035, 2125, D3125", "TR-3712E, TR-6710E", "\n8833, \n8835+, \n9330, \n9332+, \n8825+, \n9320+, \n9322+,\n2135, \n6035, \nD3135,\n D9035" +
            ",\n 2125, \nD3125,\nTR-3712E, \nTR-6710E,\nDT-1135E", "17", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("9", "N", "Amiante - Section 3 : Intervention & Maintenance", "1332-21-4", "P3", "", "", "", "", "", "8833, 8835+, 9330, 9332+", "", "2135, 6035, D3135, D9035", "TR-3712E, TR-6710E", "8833,\n 8835+, \n9330,\n 9332+,\n2135,\n 6035,\n D3135,\n D9035,\nTR-3712E,\n TR-6710E,\nDT" +
            "-1135E", "11", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("10", "N", "Ozone", "10028-15-6", "Oz", "", "", "", "", "", "9936, 9922, 9925, 9928", "", "6038, 2138, D3138, 2128, D3128", "", "9936, \n9922,\n 9925,\n 9928,\n6038,\n 2138, \nD3138, \n2128, \nD3128", "9", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("11", "N", "Styrène", "100-42-5", "A", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", "4251+,\n 4255+,\n 4277+, \n4279+,\n6051, \nD8051,\n 6055, \nD8055,\n 6057,\n 6075,\n 6059, " +
            "\nD8059\nTR-6110E, \nTR-6310E,\n TR-6130E, \nTR-6580E,\nDT-4001E, DT-4005E, DT-4006E,\n" +
            "DT-4005E, DT-4006E, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "27", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("12", "N", "Styrène", "100-42-5", "A", "", "Yes", "", "", "", "", "4251+, 4255+, 4277+, 4279+", @"6051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099 ", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", @"4251+,
 4255+,
 4277+, 
4279+,
6051+5911+501, 
6051+5925+501,
 6051+5935+501, 
D8051+D7915+D701,
 D8051+D7925+D701, 
D8051+D7935+D701, 
6055+5911+501, 
6055+5925+501,
 6055+5935+501,
 D8055+D7915+D701,
 D8055+D7925+D701,
 D8055+D7935+D701,
  6057+5911+501, 
6057+5925+501, 
6057+5935+501,
  6075+5911+501, 
6075+5925+501,
 6075+5935+501,
  6059+5911+501,
 6059+5925+501,
 6059+5935+501,
 D8059+D7915+D701, 
D8059+D7925+D701,
 D8059+D7935+D701,
 6091,
 6095,
 D8095,
 6096, 
D8094,
 6092, 
6099 
TR-6110E, 
TR-6310E,
 TR-6130E, 
TR-6580E,
DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E,
DT-4001E, DT-4005E, DT-4006E, ", "48", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("13", "N", "Styrène", "100-42-5", "A", "", "No", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", "4251+,\n 4255+,\n 4277+, \n4279+,\n6051, \nD8051, \n6055, \nD8055,\n 6057, \n6075, \n6059, " +
            "\nD8059,\nTR-6110E, \nTR-6310E,\n TR-6130E, \nTR-6580E,\nDT-4001E, DT-4005E, DT-4006E," +
            " DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "25", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("14", "N", "Styrène", "100-42-5", "A", "", "No", "Reusable", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6055, D8055, 6057, 6075, 6059, D8059", "", "6051,\n D8051,\n 6055, \nD8055,\n 6057,\n 6075,\n 6059,\n D8059,\nDT-4001E,\n DT-4005E,\n D" +
            "T-4006E,\n4251+,\n 4255+,\n 4277+,\n 4279+", "15", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("15", "N", "Styrène", "100-42-5", "A", "", "No", "PAPR", "", "", "", "", "", "TR-6110E, TR-6310E, TR-6130E, TR-6580E,DT-4001E, DT-4005E, DT-4006E, DT-4031E, DT" +
            "-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "TR-6110E, \nTR-6310E,\n TR-6130E, \nTR-6580E,\nDT-4001E, DT-4005E, DT-4006E, DT-4031E" +
            ", DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "13", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("16", "N", "Acide acrylique triester de 2-éthyl 2 (hydroxyméthyl) 1,3-propanediol", "3290-92-4", "A/P", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", @"6051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099 ", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", @"6051+5911+501, 
6051+5925+501,
 6051+5935+501, 
D8051+D7915+D701,
 D8051+D7925+D701, 
D8051+D7935+D701, 
6055+5911+501, 
6055+5925+501, 
6055+5935+501, 
D8055+D7915+D701, 
D8055+D7925+D701,
 D8055+D7935+D701, 
 6057+5911+501, 
6057+5925+501,
 6057+5935+501,  
6075+5911+501,
 6075+5925+501, 
6075+5935+501,  
6059+5911+501, 
6059+5925+501, 
6059+5935+501,
 D8059+D7915+D701,
 D8059+D7925+D701, 
D8059+D7935+D701, 
6091, 
6095,
 D8095, 
6096,
 D8094, 
6092, 
6099 ,
4251+, 
4255+, 
4277+, 
4279+,
TR-6110E, 
TR-6310E, 
TR-6130E, 
TR-6580E,
 DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E,
DT-4001E, DT-4005E, DT-4006E,", "48", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("17", "N", "Phénol", "108-95-2", "A/P1", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", @"6051+5911+501, 6051+5925+501, 6051+5935+501, D8051+D7915+D701, D8051+D7925+D701, D8051+D7935+D701, 6055+5911+501, 6055+5925+501, 6055+5935+501, D8055+D7915+D701, D8055+D7925+D701, D8055+D7935+D701,  6057+5911+501, 6057+5925+501, 6057+5935+501,  6075+5911+501, 6075+5925+501, 6075+5935+501,  6059+5911+501, 6059+5925+501, 6059+5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099 ", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", @"4251+, 
4255+,
 4277+, 
4279+,
6051+5911+501, 
6051+5925+501, 
6051+5935+501, 
D8051+D7915+D701,
 D8051+D7925+D701, 
D8051+D7935+D701, 
6055+5911+501, 
6055+5925+501, 
6055+5935+501,
 D8055+D7915+D701,
 D8055+D7925+D701,
 D8055+D7935+D701, 
 6057+5911+501,
 6057+5925+501, 
6057+5935+501,  
6075+5911+501, 
6075+5925+501, 
6075+5935+501, 
 6059+5911+501, 
6059+5925+501,
 6059+5935+501,
 D8059+D7915+D701,
 D8059+D7925+D701,
 D8059+D7935+D701,
 6091,
 6095, 
D8095,
 6096,
 D8094,
 6092, 
6099 ,
TR-6110E,
 TR-6310E, 
TR-6130E,
 TR-6580E,
DT-4001E, DT-4005E, DT-4006E, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "48", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("18", "N", "Dactin", "118-52-5", "A/P2", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", @"6051+5925+501, 6051+5935+501, D8051+D7925+D701, D8051+D7935+D701, 6055+5925+501, 6055+5935+501, D8055+D7925+D701, D8055+D7935+D701, 6057+5925+501, 6057+5935+501, 6075+5925+501, 6075+5935+501, 6059+5925+501, 6059+5935+501, D8059+D7925+D701, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, 6092, 6099 ", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", @"4251+,
 4255+, 
4277+, 
4279+,
6051+5925+501, 
6051+5935+501, 
D8051+D7925+D701, 
D8051+D7935+D701, 
6055+5925+501,
 6055+5935+501,
 D8055+D7925+D701,
 D8055+D7935+D701, 
6057+5925+501, 
6057+5935+501, 
6075+5925+501, 
6075+5935+501, 
6059+5925+501, 
6059+5935+501, 
D8059+D7925+D701, 
D8059+D7935+D701, 
6091,
 6095,
 D8095,
 6096,
 D8094,
 6092, 
6099 ,
TR-6110E,
 TR-6310E, 
TR-6130E, 
TR-6580E,
DT-4001E, DT-4005E, DT-4006E,
DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "40", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("19", "N", "4-Nitroaniline", "100-01-6", "A/P3", "", "", "", "", "", "", "", "6051+5935+501, D8051+D7935+D701, 6055+5935+501, D8055+D7935+D701, 6057+5935+501, " +
            "6075+5935+501, 6059+5935+501, D8059+D7935+D701, 6091, 6095, D8095, 6096, D8094, " +
            "6092, 6099 ", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", @"6051+5935+501, 
D8051+D7935+D701, 
6055+5935+501, 
D8055+D7935+D701, 
6057+5935+501, 
6075+5935+501, 
6059+5935+501, 
D8059+D7935+D701,
 6091,
 6095,
 D8095,
 6096, 
D8094, 
6092,
 6099 ,
TR-6110E,
 TR-6310E,
 TR-6130E, 
TR-6580E,
DT-4001E, DT-4005E, DT-4006E, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "28", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("20", "N", "Butadiène-1,3", "106-99-0", "AX", "", "", "", "", "", "", "", "6098", " DT-4007E, DT-4047E, DT-4048E", "6098,\n DT-4007E, DT-4047E, DT-4048E", "4", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("21", "N", "Triéthylamine", "121-44-8", "A\nK", "", "", "", "", "", "", "4251+, 4255+, 4277+, 4279+", "6051, D8051, 6054, 6055, D8055, 6057, 6075, 6059, D8059", "TR-6110E, TR-6310E, TR-6130E, TR-6580E", "4251+,\n 4255+, \n4277+,\n 4279+,\n6051, \nD8051, \n6054, \n6055, \nD8055, \n6057,\n 6075,\n" +
            " 6059,\n D8059,\nTR-6110E, \nTR-6310E, \nTR-6130E,\n TR-6580E,\nDT-4001E, DT-4005E, DT" +
            "-4006E, DT-4031E, DT-4035E, DT-4036E, DT-4041E, DT-4045E, DT-4046E", "26", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("22", "N", "Acide fluorhydrique", "7664-39-3", "HF", "", "", "", "", "", "", "4277+, 4279+", "6038, 6057, 6059, D8059", "TR-3822E, TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \n6038,\nD8059,\nTR-6130E,\n TR-6580E,\nTR-3822E,\nDT-4005E" +
            ", DT-4006E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "17", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("23", "N", "Brome", "7726-95-6", "B", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \nD8059,\nTR-6130E,\n TR-6580E,\nDT-4005E, DT-4006E, DT-4" +
            "032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "15", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("24", "N", "Chlorure d\'aluminium", "7446-70-0", "B/P1", "", "", "", "", "", "", "4277+, 4279+", "6057+5911+501, 6057+5925+501, 6057+5935+501, 6059+5911+501, 6059+5925+501, 6059+5" +
            "935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6096, D8094, 6092" +
            ", 6099 ", "TR-6130E, TR-6580E", @"4277+, 
4279+,
6057+5911+501,
 6057+5925+501, 
6057+5935+501, 
6059+5911+501,
 6059+5925+501, 
6059+5935+501, 
D8059+D7915+D701, 
D8059+D7925+D701,
 D8059+D7935+D701, 
6096,
 D8094,
 6092,
 6099 ,
TR-6130E, 
TR-6580E,
DT-4005E, DT-4006E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "25", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("25", "N", "Uranium (composés solubles en U)", "7440-61-1", "B/P3", "", "", "", "", "", "", "4277+, 4279+", "6057+5935+501, 6059+5935+501, D8059+D7935+D701, 6096, D8094, 6092, 6099 ", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057+5935+501, \n6059+5935+501, \nD8059+D7935+D701,\n 6096, \nD8094,\n " +
            "6092,\n 6099 ,\nTR-6130E, \nTR-6580E,\nDT-4005E, DT-4006E, DT-4032E, DT-4035E, DT-40" +
            "36E, DT-4045E, DT-4046E, DT-4048E", "19", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("26", "N", "Chlore", "7782-50-5", "B\nE", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \nD8059,\nTR-6130E,\n TR-6580E,\nDT-4005E, DT-4006E, DT-4" +
            "032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "15", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("27", "", "Acide formique", "64-18-6", "B/E\nForm", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, 6075, D8059", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \n6075\nD8059,\nTR-6130E,\n TR-6580E,\nDT-4005E, DT-4006E," +
            " DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "15", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("28", "N", "Dioxyde de soufre", "7446-09-5", "E", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \nD8059,\nTR-6130E,\n TR-6580E,\nDT-4006E,  DT-4036E, DT-" +
            "4045E, DT-4046E, ", "11", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("29", "N", "Trichlorométhylsilane", "75-79-6", "E/P1", "", "", "", "", "", "", "4277+, 4279+", "6057+5911+501, 6057+5925+501, 6057+5935+501,  6059+5911+501, 6059+5925+501, 6059+" +
            "5935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6096, D8094, 609" +
            "2, 6099 ", "TR-6130E, TR-6580E", "\n\n6057+5911+501, \n6057+5925+501, \n6057+5935+501,  \n6059+5911+501, \n6059+5925+501," +
            " \n6059+5935+501, \nD8059+D7915+D701, \nD8059+D7925+D701, \nD8059+D7935+D701, \n6096," +
            " \nD8094, \n6092, \n6099 ,\n4277+,\n 4279+,\nTR-6130E, \nTR-6580E,\nDT-4036E, DT-4045E, " +
            "DT-4046E ", "20", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("30", "N", "Bisulfite de sodium", "7631-90-5", "E/P2", "", "", "", "", "", "", "4277+, 4279+", "6057+5925+501, 6057+5935+501, 6059+5925+501, 6059+5935+501, D8059+D7925+D701, D80" +
            "59+D7935+D701, 6096, D8094, 6092, 6099 ", "TR-6130E, TR-6580E", "6057+5925+501, \n6057+5935+501, \n6059+5925+501, \n6059+5935+501, \nD8059+D7925+D701," +
            " \nD8059+D7935+D701, \n6096, \nD8094, \n6092, \n6099 ,\n4277+, \n4279+,\nTR-6130E, \nTR-6" +
            "580E,\nDT-4006E, DT-4036E, DT-4045E, DT-4046E", "18", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("31", "N", "Acide trichloroacétique", "76-03-9", "A/E", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \nD8059,\nTR-6130E, \nTR-6580E,\nDT-4006E, DT-4036E, DT-4" +
            "045E, DT-4046E", "11", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("32", "N", "Acide acétique", "64-19-7", "ABE", "", "", "", "", "", "", "4277+, 4279+", "6057, 6059, D8059", "TR-6130E, TR-6580E", "4277+,\n 4279+,\n6057, \n6059, \nD8059,\nTR-6130E, \nTR-6580E,\nDT-4006E, DT-4036E, DT-4" +
            "045E, DT-4046E", "11", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("33", "N", "Acide peracétique", "79-21-0", "ABE/P1", "", "", "", "", "", "", "4277+, 4279+", "6057+5911+501, 6057+5925+501, 6057+5935+501, 6059+5911+501, 6059+5925+501, 6059+5" +
            "935+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, 6096, D8094, 6092" +
            ", 6099 ", "TR-6130E, TR-6580E", "6057+5911+501, \n6057+5925+501, \n6057+5935+501, \n6059+5911+501, \n6059+5925+501, \n6" +
            "059+5935+501, \nD8059+D7915+D701, \nD8059+D7925+D701, \nD8059+D7935+D701, \n6096,\nD8" +
            "094, \n6092, \n6099 ,\n4277+,\n4279+,\nTR-6130E,\nTR-6580E,\nDT-4036E, DT-4045E, DT-404" +
            "6E", "20", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("34", "N", "Formaldéhyde", "50-00-0", "Form\nB", "", "", "", "", "", "", "4279+", "6075, 6059, D8059", "TR-6580E", "4279+,\n6075,\n 6059, \nD8059,\nTR-6580E,\nDT-4005E, DT-4006E, DT-4032E, DT-4035E, DT-" +
            "4036E, DT-4045E, DT-4046E, DT-4048E", "13", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("35", "N", "Formaldéhyde", "50-00-0", "Form\nB", "", "Yes", "", "", "", "", "4279+", "6059+5911+501, 6059+5925+501, 6059+5935+501,6075+5911+501, 6075+5925+501, 6075+59" +
            "35+501, D8059+D7915+D701, D8059+D7925+D701, D8059+D7935+D701, D8094, 6092, 6099 " +
            "", "TR-6580E", @"6059+5911+501, 
6059+5925+501, 
6059+5935+501,
6075+5911+501, 
6075+5925+501, 
6075+5935+501, 
D8059+D7915+D701, 
D8059+D7925+D701, 
D8059+D7935+D701, 
D8094, 
6092, 
6099 ,
4279+,
TR-6580E,
DT-4005E, DT-4006E, DT-4032E, DT-4035E, DT-4036E, DT-4045E, DT-4046E, DT-4048E", "22", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("36", "N", "Ammoniac", "7664-41-7", "K", "", "", "", "", "", "", " 4279+", "6054, 6059, D8059", "TR-6580E", " 4279+,\nTR-6580E,\n6054, \n6059, \nD8059,\nDT-4006E, DT-4045E, DT-4046E", "8", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("37", "N", "Chlorure d\'ammonium (liquides)", "12125-02-9", "K/P2", "", "", "", "", "", "", " 4279+", "6054+5925+501, 6054+5935+501, 6059+5925+501, 6059+5935+501, D8059+D7925+D701, D80" +
            "59+D7935+D701, D8094, 6092, 6099 ", "TR-6580E", "6054+5925+501, \n6054+5935+501, \n6059+5925+501, \n6059+5935+501, \nD8059+D7925+D701," +
            " \nD8059+D7935+D701, \nD8094, \n6092, \n6099 ,\n4279+,\nTR-6580, \nDT-4045E, DT-4046E", "13", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("38", "N", "Mercure vapeurs", "7439-97-6", "Hg/P3", "", "", "", "", "", "", "", "6096, 6099", "TR-6580E", "6096, \n6099,\nTR-6580E, \nDT-4046E, DT-4049E", "5", "", "France", new string[] {
                "source:Select_Testcases_France.xlsx:sheet1"}, Category="source:Select_Testcases_France.xlsx:sheet1")]
        public virtual void ValidateTheCartidges_(
                    string s_No, 
                    string is_Mixture, 
                    string contaminant, 
                    string casNumber, 
                    string recommended_Respirator, 
                    string gases_Or_Vapors_Also_Present, 
                    string particles_Present, 
                    string respirator_Type, 
                    string filter_Class, 
                    string cartidge, 
                    string disposable, 
                    string resusableFacepiece_And_Filter_Together_As_Complete_System, 
                    string resuableCartidgeFilter, 
                    string pAPRCartidgeFilter, 
                    string total_Contaminants, 
                    string total_Element_Count, 
                    string text_Message, 
                    string region, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate the Cartidges.", null, @__tags);
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
 testRunner.Given("I have navigated to the SLS Website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.When(string.Format("I select the  {0} provided  and click on the next button", region), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.Then("I select Cartidge/Filter check box and proceed further till data validation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
 testRunner.And(string.Format("I have {0} and {1} to filter the product and I filter the product", casNumber, contaminant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then(string.Format("I select the filtered products using the Cas {0} or the Contaminants Value {1}", casNumber, contaminant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("Click on the next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then(string.Format("I Filter the contaminants using the filter values {0},{1},{2},{3},{4},{5} and {6}" +
                        "", gases_Or_Vapors_Also_Present, particles_Present, respirator_Type, filter_Class, cartidge, casNumber, text_Message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And(string.Format("I do the final validation of the elements with the serial no. {0} , {1},{2},{3} a" +
                        "nd {4}", s_No, casNumber, region, text_Message, total_Element_Count), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
