// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SelectCartridgeChile.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ChileSelect")]
    public partial class ChileSelectFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ChileSelect.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ChileSelect", "\talidate the total cartidges for the below scenarios.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Validate the Cartidges.")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.TestCaseAttribute("1", "no", "Alcohol de madera", "67-56-1", "SA", "", "", "", "", "", "", "", "", "", "", "", "0", @"3M no tiene un filtro apropiado para uno o más de sus contaminantes. Los respiradores con suministro de aire pueden ser apropiados para ayudar a reducir la exposición dependiendo del factor de protección del respirador elegido. Consulte ""Recursos"" a continuación o comuníquese con el 600 300 3636 para obtener más información.", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("2", "no", "Bromuro de Cianógeno", "506-68-3", "F(SA)", "", "", "", "", "", "", "", "", "", "", "", "0", @"3M no tiene un filtro apropiado para uno o más de sus contaminantes. Los respiradores con suministro de aire pueden ser apropiados para ayudar a reducir la exposición dependiendo del factor de protección del respirador elegido. Consulte ""Recursos"" a continuación o comuníquese con el 600 300 3636 para obtener más información.", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("3", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "", "", "", "", "", "", "8210, 8210V, 8511,8515, 9105, 8233, 9322+, 9332+", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "8210,\n8210V,\n8511,\n8515,\n9105,\n8233,\n9322+,\n9332+,\n2071,\n2091,\n2291,\n7093,\n450-00" +
            "-25,\n837020,\nTR-3712E,\nTR-6710E", "16", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("4", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "No", "No", "", "Disposable", "", "", "8210, 8210V, 8511,\n8515,\n9105, 8233, 9322+, 9332+", "", "", "", "8210,\n8210V,\n8511,\n8515,\n9105,\n8233,\n9322+,\n9332+", "8", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("5", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "No", "No", "", "Reusable", "", "", "", "", "2071, 2091, 2291, 7093 ", "", "2071, 2091, 2291, 7093 ", "4", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("6", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "No", "No", "", "PAPR", "", "", "", "", "", "450-00-25, 837020, TR-3712E, TR-6710E", "450-00-25, 837020, TR-3712E, TR-6710E", "4", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("7", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "Yes", "No", "", "", "", "", "9322+, 9332+", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "9322+,\n9332+,\n2071,\n2091,\n2291,\n7093,\n450-00-25,\n837020,\nTR-3712E,\nTR-6710E", "10", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("8", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "Yes", "Yes", "", "", "", "", "8247, 8577,9936", "", "2096, 2296, 2097, 2297, 7093C", "TR-6820E ", "8247,\n8577,\n9936\n2096,\n2296,\n2097,\n2297,\n7093C\nTR-6820E", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("9", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "No", "Yes", "", "", "", "", " 8247, 8577,9936", "", "2096, 2296, 2097, 2297, 7093C", "TR-6820E ", "\n8247,\n8577,\n9936,\n2096,\n2296,\n2097,\n2297,\n7093C\nTR-6820E", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("10", "no", "Ácido 2-Fosfono-1,2,4-butanetricarboxilico", "37971-36-1", "N95", "No", "No", "", "", "", "", "8210, 8210V, 8511,8515, 9105, 8233, 9322+, 9332+", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "8210,\n8210V,\n8511,\n8515,\n9105,\n8233,\n9322+,\n9332+,\n2071,\n2091,\n2291,\n7093,\n450-00" +
            "-25,\n837020,\nTR-3712E,\nTR-6710E", "16", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("11", "no", "Ácido 4-Hidroxibenzóico", "99-96-7", "(F)N95", "", "", "", "", "", "", "", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "2071,\n2091,\n2291,\n7093,\n450-00-25,\n837020,\nTR-3712E,\nTR-6710E", "8", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("12", "no", "Aceite de Parafina", "8012-95-1", "R95\nP95", "", "", "", "", "", "", "9322+, 9332+", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "9322+, \n9332+,\n2071,\n2091,\n2291,\n7093,\n450-00-25,\n837020,\nTR-3712E,\nTR-6710E", "10", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("13", "no", "Dinitro-o-cresol", "534-52-1", "P95", "", "", "", "", "", "", "9322+, 9332+", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "9322+, \n9332+,\n2071,\n2091,\n2291,\n7093,\n450-00-25,\n837020,\nTR-3712E,\nTR-6710E", "10", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("14", "no", "Dibromoneopentil glicol", "3296-90-0", "(F)R95/P95", "", "", "", "", "", "", "", "", "2071, 2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "2071,\n2091,\n2291,\n7093,\n450-00-25,\n837020,\nTR-3712E,\nTR-6710E", "8", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("15", "no", "Aresenato de Calcio (como As)", "7778-44-1", "N100", "", "", "", "", "", "", "8233, 9332+", "", "2091, 2291, 7093 ", "450-00-25, 837020, TR-3712E, TR-6710E", "8233,\n9332+,\n2091,\n2291,\n7093,\n450-00-25,\n837020,\nTR-3712E,\nTR-6710E", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("16", "no", "Ozono", "10028-15-6", "OZ", "", "", "", "", "", "", "", "", "2097, 2297", "", "2097, 2297", "2", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("17", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "", "", "", "", "", "", "", "", "6001, 6003, 6005, 6006, 6007", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "6001,\n6003,\n6005,\n6006,\n6007,\n453-00-25,\nTR-6110E,\nTR-6310E,\n837242,\n456-18-25,\nT" +
            "R-6130E,\n453-09-25,\nTR-6580E\n837020+837242", "14", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("18", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "", "", "No", "Reusable", "", "", "", "", "6001, 6003, 6005, 6006, 6007", "", "6001, 6003, 6005, 6006, 6007", "5", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("19", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "", "", "No", "PAPR", "", "", "", "", "", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("20", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "", "", "No", "", "", "", "", "", "6001, 6003, 6005, 6006, 6007", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "6001, 6003, 6005, 6006, 6007,453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR" +
            "-6130E, 453-09-25, TR-6580E,837020+837242", "14", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("21", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "", "", "Yes", "", "", "", "", "", @"6001+5N11+501, 6001+502+2071, 6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+5N11+501, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+5N11+501, 6005+502+2071, 6005+502+2091, 6005+502+2291, 6005+502+7093, 6006+5N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+5N11+501, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+5N11+501,
6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+5N11+501,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "38", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("22", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "No", "", "Yes", "", "", "", "", "", @"6001+5N11+501,6001+502+2071,6001+502+2091, 6001+502+2291,6001+502+7093, 6003+5N11+501, 6003+502+2071, 6003+502+2091,6003+502+2291,6003+502+7093,
6005+5N11+501,6005+502+2071,6005+502+2091, 6005+502+2291,6005+502+7093,6006+5N11+501, 6006+502+2071, 6006+502+2091,6006+502+2291,6006+502+7093, 6007+5N11+501, 6007+502+2071, 6007+502+2091,6007+502+2291,6007+502+7093,60921,60923,60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+5N11+501,
6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+5N11+501,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "38", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("23", "no", "Acetato de 1,1 Dimetilpropil", "625-16-1", "OV", "Yes", "", "Yes", "", "", "", "", "", @"6001+502+2071, 6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+502+2071, 6005+502+2091, 6005+502+2291,6005+502+7093, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "33", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("24", "no", "Acetato de 2-Metilpropilo", "110-19-0", "(F)OV", "", "", "", "", "", "", "", "", "6001, 6003, 6005, 6006, 6007", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "6001,\n6003,\n6005,\n6006,\n6007,\n453-00-25,\nTR-6110E,\nTR-6310E,\n837242,\n456-18-25,\nT" +
            "R-6130E,\n453-09-25,\nTR-6580E,\n837020+837242", "14", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("25", "no", "Dietilamina", "109-89-7", "(F)AM\n(F)OV", "", "", "", "", "", "", "", "", "6001, 6003, 6004, 6005, 6006, 6007", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "6001,\n6003,\n6004,\n6005,\n6006,\n6007,\n453-00-25,\nTR-6110E,\nTR-6310E,\n837242,\n456-18" +
            "-25,\nTR-6130E,\n453-09-25,\nTR-6580E\n837020+837242", "15", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("26", "no", "Acetaldehído", "75-07-0", "(F)OV\n(F)MG", "", "", "", "", "", "", "", "", "6001, 6003, 6005, 6006, 6007", "453-00-25, TR-6110E, TR-6310E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,8" +
            "37020+837242", "6001,\n6003,\n6004,\n6005,\n6006,\n6007,\n453-00-25,\nTR-6110E,\nTR-6310E,\n837242,\n456-18" +
            "-25,\nTR-6130E,\n453-09-25,\nTR-6580E\n837020+837242", "15", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("27", "no", "Acetamida", "60-35-5", "OV/N95", "", "", "", "", "", "", "", "", @"6001+5N11+501, 6001+502+2071, 6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+5N11+501, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+5N11+501, 6005+502+2071, 6005+502+2091, 6005+502+2291, 6005+502+7093, 6006+5N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+5N11+501, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+5N11+501,
6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+5N11+501,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "38", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("28", "no", "Ácido 2,2-Dicloropropíonico", "75-99-0", "(F)OV/N95", "", "", "", "", "", "", "", "", @"6001+5N11+501, 6001+502+2071, 6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+5N11+501, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+5N11+501, 6005+502+2071, 6005+502+2091, 6005+502+2291, 6005+502+7093, 6006+5N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+5N11+501, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+5N11+501,
6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+5N11+501,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "38", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("29", "no", "Arsénico, compuestos orgánincos (como As)", "varies", "OV/N100", "", "", "", "", "", "", "", "", @"6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+502+2091, 6005+502+2291, 6005+502+7093, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "28", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("30", "no", "Aceite astral (como vapor total de hidrocarburos)", "68334-30-5", "OV/P95", "", "", "", "", "", "", "", "", @"6001+502+2071, 6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+502+2071, 6005+502+2091, 6005+502+2291,6005+502+7093, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "33", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("31", "no", "Bifenilo policlorado (42% clorado)", "53469-21-9", "(F)OV/P95", "", "", "", "", "", "", "", "", @"6001+502+2071, 6001+502+2091, 6001+502+2291, 6001+502+7093, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6005+502+2071, 6005+502+2091, 6005+502+2291,6005+502+7093, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60921, 60923, 60925, 60926, 60927", "453-00-25, TR-6110E, TR-6310E, 837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-" +
            "6580E", @"6001+502+2071,
6001+502+2091,
6001+502+2291,
6001+502+7093,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6005+502+2071,
6005+502+2091,
6005+502+2291,
6005+502+7093,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60921,
60923,
60925,
60926,
60927,
453-00-25,
TR-6110E,
TR-6310E,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "33", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("32", "no", "Ácido Fluorhídrico", "7664-39-3", "(F)HF", "", "", "", "", "", "", "", "", "7093C, 6003, 6006", "TR-6820E, 837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "7093C,\n6003,\n6006,\nTR-6820E,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n83" +
            "7020+837242", "10", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("33", "no", "Cloro", "7782-50-5", "(F)Cl", "", "", "", "", "", "", "", "", "6002, 6003, 6006, 6007", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6002,\n6003,\n6006,\n6007,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n837020+" +
            "837242", "10", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("34", "no", "Ácido Clorhídrico", "7647-01-0", "AG", "", "", "", "", "", "", "", "", "6002, 6003, 6006", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6002,\n6003,\n6006,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n837020+837242" +
            "", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("35", "no", "Bromo", "7726-95-6", "(F)AG", "", "", "", "", "", "", "", "", "6002, 6003, 6006, 6007", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6002,\n6003,\n6006,\n6007,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n837020+" +
            "837242", "10", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("36", "no", "Ácido Nitrilotrimetanofosfónico", "6419-19-8", "AG/N95", "", "", "", "", "", "", "", "", @"6002+5N11+501, 6002+502+2071, 6002+502+2091, 6002+502+2291, 6002+502+7093, 6003+5N11+501, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6006+5N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+5N11+501, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60922, 60923, 60926, 60927", "837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E", @"6002+5N11+501,
6002+502+2071,
6002+502+2091,
6002+502+2291,
6002+502+7093,
6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60922,
60923,
60926,
60927,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "29", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("37", "no", "Ácido Clorosulfónico", "7790-94-5", "(F)AG/N95", "", "", "", "", "", "", "", "", @"6002+5N11+501, 6002+502+2071, 6002+502+2091, 6002+502+2291, 6002+502+7093, 6003+5N11+501, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6006+5N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+5N11+501, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60922, 60923, 60926, 60927", "837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E", @"6002+5N11+501,
6002+502+2071,
6002+502+2091,
6002+502+2291,
6002+502+7093,
6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60922,
60923,
60926,
60927,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "29", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("38", "no", "Ácido 2-Cloropropiónico", "598-78-7", "OV/AG", "", "", "", "", "", "", "", "", "6003, 6006, 6007", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6003,\n6006,\n6007,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n837020+837242" +
            "", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("39", "no", "Ácido Acético", "64-19-7", "(F)OV/AG", "", "", "", "", "", "", "", "", "6003, 6006, 6007", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6003,\n6006,\n6007,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E\n837020+837242", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("40", "no", "a-Clorobenzaldehído", "98-88-4", "(F)OV/AG\n(F)MG", "", "", "", "", "", "", "", "", "6003, 6006, 6007", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6003,\n6006,\n6007,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n837020+837242" +
            "", "9", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("41", "no", "Acido Paracetico", "79-21-0", "(F)OV/AG/N95", "", "", "", "", "", "", "", "", "6003+5N11+501, 6003+502+2071, 6003+502+2091, 6003+502+2291, 6003+502+7093, 6006+5" +
            "N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 6007+5N11+5" +
            "01, 6007+502+2071, 6007+502+2091, 6007+502+2291, 6007+502+7093, 60923, 60926, 60" +
            "927", "837020+837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E", @"6003+5N11+501,
6003+502+2071,
6003+502+2091,
6003+502+2291,
6003+502+7093,
6006+5N11+501,
6006+502+2071,
6006+502+2091,
6006+502+2291,
6006+502+7093,
6007+5N11+501,
6007+502+2071,
6007+502+2091,
6007+502+2291,
6007+502+7093,
60923,
60926,
60927,
837020+837242,
456-18-25,
TR-6130E,
453-09-25,
TR-6580E", "23", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("42", "no", "1-Aminobutano", "109-73-9", "AM", "", "", "", "", "", "", "", "", "6004, 6006", "453-09-25, TR-6580E", "6004,\n6006,\n453-09-25,\nTR-6580E", "4", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("43", "no", "Amoniaco", "7664-41-7", "(F)AM", "", "", "", "", "", "", "", "", "6004, 6006", "453-09-25, TR-6580E", "6004,\n6006,\n453-09-25,\nTR-6580E", "4", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("44", "no", "Cloruro de amonio (líquidos)", "12125-02-9", "AM/N95", "", "", "", "", "", "", "", "", "6004+5N11+501, 6004+502+2071, 6004+502+2091, 6004+502+2291, 6004+502+7093, 6006+5" +
            "N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 60924, 6092" +
            "6", "453-09-25, TR-6580E", "6004+5N11+501,\n6004+502+2071,\n6004+502+2091,\n6004+502+2291,\n6004+502+7093,\n6006+5" +
            "N11+501,\n6006+502+2071,\n6006+502+2091,\n6006+502+2291,\n6006+502+7093,\n60924,\n6092" +
            "6,\n453-09-25,\nTR-6580E", "14", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("45", "no", "Formaldehído", "50-00-0", "(F)Form", "", "", "", "", "", "", "", "", "6005, 6006", "", "6005, 6006", "2", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("46", "no", "Ácido fórmico", "64-18-6", "(F)AG\n(F)Form", "", "", "", "", "", "", "", "", "6002, 6003, 6005, 6006, 6007", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6002,\n6003,\n6005,\n6006,\n6007,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n8" +
            "37020+837242", "11", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("47", "no", "Cianógeno", "460-19-5", "MG", "", "", "", "", "", "", "", "", "6006", "453-09-25, TR-6580E", "6006,\n453-09-25,\nTR-6580E\n", "3", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("48", "no", "Ácido clorofórmico dimetilamida", "79-44-7", "(F)MG", "", "", "", "", "", "", "", "", "6006", "453-09-25, TR-6580E", "6006,\n453-09-25,\nTR-6580E\n", "3", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("49", "no", "Yodo", "7553-56-2", "(F)MG/N95", "", "", "", "", "", "", "", "", "6006+5N11+501, 6006+502+2071, 6006+502+2091, 6006+502+2291, 6006+502+7093, 60926", "453-09-25, TR-6580E", "6006+5N11+501,\n6006+502+2071,\n6006+502+2091,\n6006+502+2291,\n6006+502+7093,\n60926," +
            "\n453-09-25,\nTR-6580E", "8", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("50", "no", "Arsénico, compuestos inorgánicos (excepeto Arsina) (como As)", "varies", "MG/N100", "", "", "", "", "", "", "", "", "6006+502+2091, 6006+502+2291, 6006+502+7093, 60926", "453-09-25, TR-6580E", "6006+502+2091,\n6006+502+2291,\n6006+502+7093,\n60926,\n453-09-25,\nTR-6580E", "6", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("51", "no", "Hg", "7439-97-6", "Hg", "", "", "", "", "", "", "", "", "6007", "TR-6580E", "6007,\nTR-6580E", "2", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        [NUnit.Framework.TestCaseAttribute("52", "no", "Dióxido de cloro", "10049-04-4", "AG", "", "", "", "", "", "", "", "", "6002, 6006", "837242, 456-18-25, TR-6130E, 453-09-25, TR-6580E,837020+837242", "6002,\n6006,\n837242,\n456-18-25,\nTR-6130E,\n453-09-25,\nTR-6580E,\n837020+837242", "8", "", "Chile", new string[] {
                "source:chile_data_new.xlsx:sheet1"}, Category="source:chile_data_new.xlsx:sheet1")]
        public virtual void ValidateTheCartidges_(
                    string s_No, 
                    string is_Mixture, 
                    string contaminant, 
                    string casNumber, 
                    string recommended_Respirator, 
                    string oil_Question, 
                    string gases_Or_Vapors_Also_Present, 
                    string particles_Present, 
                    string respirator_Type, 
                    string filter_Class, 
                    string cartidge, 
                    string disposable, 
                    string resusableFacepiece_And_Filter_Together_As_Complete_System, 
                    string resuableCartidgeFilter, 
                    string pAPRCartidgeFilter, 
                    string total_Contaminants, 
                    string total_Element_Count, 
                    string text_Message, 
                    string region, 
                    string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate the Cartidges.", null, @__tags);
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
 testRunner.Given("I have navigated to the SLS Website", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then(string.Format("I select the  {0} provided  and click on the next button", region), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.Then("I select Cartidge/Filter check box and proceed further till data validation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 8
 testRunner.Then(string.Format("I have {0} and {1} to filter the product and I filter the product", casNumber, contaminant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.Then(string.Format("I select the filtered products using the Cas {0} or the Contaminants Value {1}", casNumber, contaminant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("Click on the next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then(string.Format("I Filter the contaminants using the filter values {0},{1},{2},{3},{4},{5},{6} and" +
                        " {7}", gases_Or_Vapors_Also_Present, oil_Question, particles_Present, respirator_Type, filter_Class, cartidge, casNumber, text_Message), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.Then(string.Format("I do the final validation of the elements with the serial no. {0} , {1},{2},{3} a" +
                        "nd {4}", s_No, casNumber, region, text_Message, total_Element_Count), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
